export const config = {
  SECRET_SANTA_API_BASE_URL: process.env.NEXT_PUBLIC_SECRET_SANTA_API_BASE_URL,
  REGISTER_URL: process.env.NEXT_PUBLIC_REGISTER_URL!,

  GET_MEMBER_GROUP_URL: process.env.NEXT_PUBLIC_GET_MEMBER_GROUP_URL!,
  GET_GROUP_MEMBERS_URL: process.env.NEXT_PUBLIC_GET_GROUP_MEMBERS_URL!,
};
